### ISSUE TITLE
vt_kable_test_code is latex hard coded

### ISSUE THREAD

**Issue by thebioengineer** [phuse-org/valtools#100]
This function will only work with latex due to coloring of the "pass/fail" field. how to make that more genera.
 TODO:
- How to allow coloring of text in a generic multi-output way

**Comment by mariev** [comment]
should we depend on {colortable} 😏

**Comment by thebioengineer** [comment]
Gotta get that on CRAN then 😂

**Comment by thebioengineer** [comment]
option 2: remove coloring. Color is nice to call out pass/fail, but is that necessary?

**Comment by thebioengineer** [comment]
https://datadojo.dev/2018/11/05/formatting-tables-in-r-markdown-with-kableextra/
use cell spec to set color
