### ISSUE TITLE
how to capture deprecated requirements/test cases?

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#118]
need test cases to demonstrate this

**Comment by mariev** [comment]
use custom `@deprecated`

**Comment by mariev** [comment]
@thebioengineer can we add this to the `vt_scrape_test_code_editors` usage?

**Comment by thebioengineer** [comment]
that makes sense to me. Do you want to add it in PR #151 ?

**Comment by thebioengineer** [comment]
Can we close this one out?

**Comment by mariev** [comment]
closed via #154
