### ISSUE TITLE
getting package name

### ISSUE THREAD

**Issue by thebioengineer** [phuse-org/valtools#119]
Currently we have a lot of code trying to figure out the package being validated, and different techniques (dirnames, desc, etc) - would it make sense to add it into the validation.yml on creation? 

Benefits:
- consistent location & function to grab this info (?`get_config_package()`)
- documented intent of validation

Difficulty
- Would need to be determined on creation of validation.yml - I dont think thats a huge barrier

**Comment by thebioengineer** [comment]
@elimillera @mariev - what do you think?

**Comment by mariev** [comment]
👍  absolutely! mentioned here: https://github.com/phuse-org/valtools/pull/116#discussion_r622387375

As a naiive implementation, validation_report is now assuming the "package name" is:
```
root <- find_root(has_file(".here") | is_rstudio_project | is_r_package | is_vcs_root)
```
