### ISSUE TITLE
vt_scrape_val_env & suggested packages

### ISSUE THREAD

**Issue by thebioengineer** [phuse-org/valtools#129]
vt_scrape_val_env assumes that all packages listed in the dependencies (depends, imports and suggests) are installed. while this does hold true for packages that are being built to be validated, but this breaks down when intending to validate an external package. 

Suggestion would be to modify the assumptions, and it should be acceptable to not get the package version for the "suggested" packages when doing an install on an external package - functionality might not be necessary.

**Comment by mariev** [comment]
closed via #132
