### ISSUE TITLE
coverage matrix if no coverage info is included

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#147]
`vt_scrape_coverage_matrix` currently throws error if coverage details is absent

PR coming shortly

**Comment by thebioengineer** [comment]
Do we want it to fail when only a few test cases have coverage? Or would it make sense to complain when coverage is missing more clearly. ie: `Error: Missing coverage documentation for test cases 2, 5, and 25`

**Comment by mariev** [comment]
Well I don't think that an org's choice to be sparse/incomplete with their coverage should block creating the coverage matrix - we actually run across this in {scharpbama} with `Process_Test_Cases_Setup.Rmd`

 Not sure how annoying having a warning would be either 😬

**Comment by thebioengineer** [comment]
good point.

**Comment by mariev** [comment]
closed via #149
