### ISSUE TITLE
why does test code result table use inconsistent numbering ?

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#150]
via function `valtools:::eval_test_code` , test ids are numbered using X.Y.Z, where position "Z" is auto-generated. However if there is only one sub test in "X.Y", i.e. only one instance of `expect_*` in `test_that(..)` {valtools} drops the "Z" position. Can we switch to using nomenclature X.Y.Z for all tests evaluated?

Due to code at:

https://github.com/phuse-org/valtools/blob/3b844a532cd87023d2e128bc136a6facb6cf513c/R/evaluate_test_code.R#L130-L135

**Comment by thebioengineer** [comment]
🤔 totally reasonable - I don't recall my reasoning behind breaking it out like that. I think it is because the assumption that the test case was written such that there were no sub numbering.
