### ISSUE TITLE
create new roxygen tags 

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#16]
create roxygen tags; 

- `@editor` : last updated by field
- `@update`: last updated date field

see discussion & example code: https://github.com/phuse-org/valtools/pull/14#issuecomment-782217914

**Comment by thebioengineer** [comment]
do we want to use `@editDate` or something more related to editor? I feel as though `@update` could be confusing?

**Comment by mariev** [comment]
closed via #17
