### ISSUE TITLE
add clarification that vt_validate_* functions need to be run from the project

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#160]
If validation lead is authoring the report interactively, it may not be obvious that `vt_validate_` will need to be run from the project i.e. package level directory. Should have an informative warning if this naive mistake is made.

**Comment by thebioengineer** [comment]
Should we make it smart enough to look up the tree?

**Comment by mariev** [comment]
that would be terrific!

**Comment by mariev** [comment]
closed via #168
