### ISSUE TITLE
vt_kable_* assumptions regarding ids

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#163]
vt_kable_* family makes some assumptions about ID structure, by concatenating prefixes to existing IDs. This can be quite ugly if users are following the conventions from the vignette. Can these be dropped?

Ex.
![image](https://user-images.githubusercontent.com/253189/119076403-57e16b80-b9a7-11eb-99a3-1c88b8c64851.png)

**Comment by thebioengineer** [comment]
I think it makes sense to verbatim report the value provided

**Comment by mariev** [comment]
closed via #164
