### ISSUE TITLE
vt_validate_* for validate separate from package

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#165]
Need command-line option for validating separate from package, e.g. to validate 3rd party package.

**Comment by mariev** [comment]
@thebioengineer can we prioritize this to unblock [PR#6](phuse-org/valtools#6) in {R_Package_Validation_Tutorial} ?

**Comment by thebioengineer** [comment]
Sure thing.

**Comment by thebioengineer** [comment]
woud this be `vt_validate_external()`? or something?

**Comment by mariev** [comment]
closed via #168
