### ISSUE TITLE
suppress dialog box

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#184]
when running `vt_validate_report`  an R gui dialog box prompting package download/update may pop up. Although this closes automatically during course of report generation, it is distracting and gives the (incorrect) impression that the user's environment is being modified. 

Recommended action is to suppress the visibility of the dialog.

**Comment by thebioengineer** [comment]
This was due to an erroneous `library()` without a package supplied, not an error in {valtools} as we assumed. Closing this issue for now.
