### ISSUE TITLE
structure of /R currently prevents usage of `devtools::document()`

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#2]
@elimillera wondering if we can move some code up the tree? Nesting functions within R/uat means we lose ability to leverage `devtools::document()` on individual functions. 

Thoughts?

**Comment by elimillera** [comment]
Hey @mariev,
Definitely. Once we have a good idea of functionality we would want to get rid of the nested folders in there

**Comment by mariev** [comment]
@elimillera can we delete the /uat/ folder?

**Comment by elimillera** [comment]
@mariev Yeah we should be good to remove all of that, There's no new stuff in there
