### ISSUE TITLE
compatibility with bookdown

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#22]
Adding bare roxygen blocks in Rmd files that are child bookdown docs throws errors. One alternative is to surround the block with yaml separators, so a requirement can look like:

```
---
#' @title Function Requirement 001
#' @editor Marie Vendettuoli
#' @editDate 2020-10-12
---

+ Requirement starts here
```

🤔 Is it too cumbersome to have `---` surrounding? Do we need to include support for bookdown? thoughts?

**Comment by thebioengineer** [comment]
Could you remind me why we were looking at using {bookdown}? Tt was for being able to have dynamic references, correct?

Overall, the `---` isn't too distracting for me. One worry though could be folks starting to think about yaml headers and be confused why we are using roxygen tags?

**Comment by mariev** [comment]
Bookdown allows usage of configuring the report via `_bookdown.yml` & `_output.yml`. 

It provides a much more accessible interface for compendiums of many child .Rmds, the tradeoff being that test code needs to be captured via .RMD not .R files.

**Comment by mariev** [comment]
@elimillera I saw your [mention](https://github.com/phuse-org/valtools/issues/44#issuecomment-792130275) of using .validation yaml in a pkgdown-like manner e.g. by being able to list ordering of reqs/test cases/ test code files. 🤔 about our past discussions re: bookdown support, and wondering if we can frame .validation as "bookdown-like"?

**Comment by thebioengineer** [comment]
are we saying we would add to .validation the configuration of the validation report?

**Comment by elimillera** [comment]
@mariev Can you clarify what you mean by bookdown-like? I was just thinking YAML would be a nice way to specify style, ordering, etc. I haven't thought about using bookdown for this context but I think that's a really good idea if we can maintain compatibility with all the tools we can.

@thebioengineer I think that would be nice functionality if people are able to specify how the report is rendered and preserver that.

**Comment by mariev** [comment]
Comparing `.validation` to the contents of `_bookdown.yml`: 

Superficially, our .validation file includes details that are captured in bookdown fields `book_filename` and `output_dir`. 

If we include a listing of req/test case/test code child files, that would add similar functionality to the `rmd_files` field.


- https://bookdown.org/yihui/bookdown/usage.html#usage
- https://bookdown.org/yihui/bookdown/configuration.html

**Comment by mariev** [comment]
summarizing today's decision via Teams mtg:

- add field for listing reqs/test case/test code files in .validation to scrape via `vt_use_report` (#45)
- change .validation to .validation.yml (#50 )
- no expectation of bookdown support.
