### ISSUE TITLE
Functionality for rendering signature table 

### ISSUE THREAD

**Issue by elimillera** [phuse-org/valtools#39]
Render signature table in the fashion of https://github.com/phuse-org/valtools/blob/scharp_legacy/R/generate_sig_tab.R while using the .validation config.

**Comment by mariev** [comment]
same comment as I had for #40  - let's give advanced users the option of having access to the r object separate from the kable rendering.

**Comment by thebioengineer** [comment]
I think this has been resolved and is in develop. Closing, but re-open if you feel as though more needs to be done.
