### ISSUE TITLE
Functionality for capturing validation environment

### ISSUE THREAD

**Issue by elimillera** [phuse-org/valtools#40]
Functionality for capturing information about environment the validation ran in.

Items:

- R installation folder
- Library Locations
- R Version
- Session Information
- Host Platform Information
- Host Machine Information
- R Installation Capabilities
- R Search Path

**Comment by thebioengineer** [comment]
was this done in #9? checking to make sure not to duplicate work!

**Comment by elimillera** [comment]
I knew this one sounded familiar. I'll mark this as complete and check off the other one
