### ISSUE TITLE
template functionality

### ISSUE THREAD

**Issue by thebioengineer** [phuse-org/valtools#5]
This package is being billed as the {usethis} and {devtools} of validation. One key element of the {usethis} magick is the template generating abilities it has. In a few short lines, you can have a package skeleton, a basic R function, unit test template, and vignette template all queued up and ready for your content. 

I believe that this should be the case as well for {valtools}, providing templates to the specs, test cases, test code and validation report. What are your thoughts, and how long do you think it would take to implement?

**Comment by elimillera** [comment]
@thebioengineer
I can start hashing this functionality out. Here are the functions I have thought of so far.
* `vt_use_validation` - Creates the directory skeleton for validation
* `vt_create_package` - Wrapper to `usethis::create_pakcage` but calls `vt_use_validation`
* `vt_new_spec` - Create/edit new specification
* `vt_new_case` - Create/edit new test case
* `vt_new_code` - Create new file for test code. similar to `usethis::use_test`
* `vt_run_validation` - Runs validation report if possible

I'm thinking the `spec` and `case` function creates both the rmd and an entry in a csv file. @mariev Would you agree with that approach? I think that would give the user the ability to track the specs/cases programmatically and let them modify it as the need too.

We could also use a csv/rdata file to handle the metadata of the spec/code and the rmd to hold the actual content. We might want to push this over to a discussion forum as well

**Comment by thebioengineer** [comment]
both the Rmd and an entry in the csv? I think we should try to steer folks to use-ing markdown because it is a much more flexible format. The code Atorus used was converting CSV into markdown, correct?

**Comment by thebioengineer** [comment]
But otherwise I am liking the names overall. Would it make sense to align more with `{usethis}` and their `use_*` nomenclature? `vt_use_spec()`, `vt_use_test_case()`

Also, I think the addition of 2 new functions might be good: `vt_validated_build()` and `vt_validate_installed_package()`.
`vt_validated_build` runs validation vignette, copies contents as described in the white paper into the `inst/validation`, and builds the package into either a binary or bundle for install. `vt_validate_installed_package()` will execute the validation report for an installed package if it was built using `vt_validated_build()` and return the report results.

**Comment by elimillera** [comment]
I like the idea to use `vt_use_`. We did use the csvs at Atorus, but now that I think more about it, we might be better off just going with the markdown files for now. We can add in the csv rendering functionality later on, I think we're most of the way there with what we have.

I also like the other two functions, can you clarify about how `vt_validated_build()` would return the results? Should it take a file path or should it just return a summary of pass/fails?

**Comment by thebioengineer** [comment]
I am thinking `vt_validated_build()` would be our version of `devtools::build()`. In my mind the process is:

1. Run validation report. (a la `vt_run_validation()`)
2. On successful completion of the report, copy all the contents that would be required to rerun the report into `inst/validation` (specs, roxygen headers for functions, test cases, test code, source code for the validation report)
3. Execute `devtools::build()` to compile into a bundle or binary depending on the input

maybe somewhere there is a `devtools::check()`?? 

And great (re markdown files for now).  think we should aim for the simplest solution for V0.1, and then we can look at providing helper functions for alternative input formats (and appropriate checking)

**Comment by thebioengineer** [comment]
@elimillera - can you add the proposed function naming to wiki?

**Comment by thebioengineer** [comment]
I think this has been resolved and is in develop. Closing, but re-open if you feel as though more needs to be done.
