### ISSUE TITLE
capture validation environment

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#7]
Due to performance differences between OS, R version and package versions, it is helpful to capture the validation environment. This should include:
- OS
- R Version
- package versions for any listed in Description "Depends" or "Imports".

**Comment by mariev** [comment]
@thebioengineer - do you think that packages loaded in the Validation report document should be listed? This may affect how the test code will evaluate...

**Comment by thebioengineer** [comment]
That would be. Good addition. But we might want to keep that separate from the dependencies of the package? Present it as the validation report dependencies or something

**Comment by mariev** [comment]
closed via #9
