### ISSUE TITLE
R objects as inputs to vt_scrape_tags_from

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#71]
When using dynamic numbering, we need to render the numbers before scraping the @coverage slot. The rendered files will be either retained as R objects or saved in a temporary location. Neither of these options play nicely with the assumptions of existing functions.

Pseudocode of proposed workflow:

```r
vector_of_test_case_files <- ...
# existing functionality 👍 
rendered_numbers_content <- lapply(vector_of_test_case_files , dynamic_reference_rendering) 

### Option 1: use R object
# this currently fails b/c requires filenames as input
coverage_details <- lapply(rendered_numbers_content,
                           vt_scrape_tags_from, type = "test_cases", tags = "coverage")

### Option 2: reading from temp files
# this currently fails due to assumptions of dir_ref and type
write_content_to_temp_files(rendered_numbers_content )
coverage_details <- lapply(list_of_temp_files,
                          vt_scrape_tags_from, type = "test_cases", tags = "coverage")
```

**Comment by mariev** [comment]
@thebioengineer it looks like we are getting into the territory of having to evaluate iteratively to populate early placeholders with details from later locations. What are your thoughts for how to capture this? Are temp files the way to go? or is it better to re-run?

**Comment by thebioengineer** [comment]
dynamic_reference_rendering could live inside the functions that read in files 🤔
so update `vt_scrape_roxygen` to be:

```r
vt_scrape_roxygen <- function(file, ..., type = tools::file_ext(file)){
  # defaults to no dynamic referencing, user must opt-into dynamic referencing by setting option to TRUE
  if(isTRUE(getOption("vt.dynamic_referencing", "FALSE"))){
    text <- dynamic_reference_rendering(file)
  }else{
    text <- readLines(file)
  }

  text <- roxy_text(
    text,
    file = file,
    class = tolower(type)
  )

  parse_roxygen(text)

}


```

**Comment by mariev** [comment]
After sleeping on this, I thought maybe I _don't_ need to render dynamics first? so that I can create the coverage matrix content using tags, and then render later, but then I run into below - looks like the "#" is getting pulled out somehow?

```r
>   cov_matrix_content <- data.frame( req_id = "##req:first",
+                                     tc_id = c("##tc:first", "##tc:second"))
>   cov_matrix_content
       req_id       tc_id
1 ##req:first  ##tc:first
2 ##req:first ##tc:second
>   references <- vt_dynamic_referencer$new()
>   references$initialize(reference_indicator = "##")
>   references$scrape_references(cov_matrix_content)
 Error: Invalid reference at: ##eq:first
Reference type indicator can only be one of: `req` or `tc`!
Run `rlang::last_error()` to see where the error occurred. 
```

**Comment by mariev** [comment]
☝️ looks like the culprit is in the `gregexpr` call from `$scrape_references`

**Comment by thebioengineer** [comment]
No, the same reference object would be used across the entire session/knit. If you don't pass a referencer to dynamic_reference_redering, it uses one stored in the environment. but we can make accessors/modifiers for advanced users.

I think if we focus on the non-dynamic referencing cases first, we can go back and add it back in as an option.

**Comment by thebioengineer** [comment]
no it uses the same reference object. dynamic_reference_rendering, if not passed a referencer, uses the global one in the package.

**Comment by thebioengineer** [comment]
This is resolved I believe. reopen if not.
