### ISSUE TITLE
kable formatting for author lists

### ISSUE THREAD

**Issue by thebioengineer** [phuse-org/valtools#83]
Missing a kable-ing function for author lists.

**Comment by mariev** [comment]
looking at usage for `vt_scrape_tags_from` and I see that we need to reshape first if we want to have a true `vt_scrape_function` experience, i.e. a data.frame that can be easily fed to `kable()` calls. Do we need to add this as well?

example:
```
all_authors <- do.call("rbind", vt_scrape_tags_from(
    type = "functions",
    tags = c("editor", "editDate", "export"),
    src = {{pkg_name}},
    ref = valtools:::get_config_working_dir()
  ))
```

**Comment by thebioengineer** [comment]
> looking at usage for `vt_scrape_tags_from` and I see that we need to reshape first if we want to have a true `vt_scrape_function` experience, i.e. a data.frame that can be easily fed to `kable()` calls. Do we need to add this as well? edit: and if so, should `vt_scrape_tags_from` migrate to an internal function?
> 
> example:
> 
> ```
> all_authors <- do.call("rbind", vt_scrape_tags_from(
>     type = "functions",
>     tags = c("editor", "editDate", "export"),
>     src = {{pkg_name}},
>     ref = valtools:::get_config_working_dir()
>   ))
> ```

I think that makes sense, and make an external "vt_scrape_authors()" function?
