### ISSUE TITLE
Handling of NEWS details

### ISSUE THREAD

**Issue by mariev** [phuse-org/valtools#93]
Historically SCHARP has used the NEWS file to capture changelog info tied to a package release. Specifically, we identify release bullets using `[validation]` and `[version date]` and scrape those elements only.  How should we handle this in {valtools} to be mindful of access differences in the validate on install vs validate after install paradigms? 

In order for validation report to render from /inst this file would need to be copied over, and I am hesitant to suggest copying of files that are part of the normal R package structure. Can we use the NEWS formatting, but call this something different, which will then live in the validation working directory?

thoughts? @thebioengineer @elimillera

**Comment by thebioengineer** [comment]
Change history documentation is pretty standard everywhere I have worked - and we should provide an avenue for it. The idea of creating a "change log" within the validation folder makes sense IMO (keeping news.md structure)

**Comment by mariev** [comment]
Listing all the functionsfiles that would be affected by this change, all test cases are in `test-news_handlers.R`

- [ ] `vt_scrape_news`
- [ ] `vt_kable_news`
- [ ] `vt_use_news` 
- [ ] `read_news`

**Comment by mariev** [comment]
@elimillera if you could weigh in, I'll jump on this pretty quickly b/c it is a blocker for the validation report templating

**Comment by thebioengineer** [comment]
resolved as of #95, reopen if not the case.
