### ISSUE TITLE
Capturing risk scores for requirements

### ISSUE THREAD

**Issue by thebioengineer** [phuse-org/valtools#99]
Right now there is no good way to capture risk scores for the requirements - people have to create a rmarkdown table, etc. 

What if we were to add a `@riskscore` roxygen tag that is similar to `@coverage` to give a location to capture this, and produce a table (if wanted) of the risk scores

```
#' @title title of my requirement
#' @editor Ellis
#' @editDate 2021-04-22
#' @riskscore
#' 1.1 : 5
#' 1.2: 2
#' 2: 10

+ 1 Capture this info
  + 1.1 record the info
  + 1.2 make info accessible
+2 Highly risky requirement

```

**Comment by mariev** [comment]
what about incorporating {riskmetric} package?

**Comment by thebioengineer** [comment]
🤔 I may be missing the point of {riskmetric}, but it looks at the package on the whole, correct? does it have ability to look at specific requirements? or were you thinking how we could work with that package?

**Comment by elimillera** [comment]
You can pass customized weights for the metrics themselves which is how the final score is computed, but I don't think that's what we're looking for here. The metrics are things like download numbers and GitHub issues statuses.

**Comment by thebioengineer** [comment]
@elimillera - Marie and I were chatting and do you think there would be value in creating an extension for {riskmetric} for it to capture the risk assessments if we were to document it this way?

**Comment by thebioengineer** [comment]
Has been addressed, and we can look at adding a riskmetric extension in the future
